return_ip

diff --git a/toast b/toast
--- a/toast
+++ b/toast
@@ -324,6 +324,17 @@ config_info() {
 }
 
 config_save() {
+    echo "server save..."
+
+    URL="${TOAST_URL}/server/config"
+    RES=`curl --data "token=${TOKEN}&no=${SNO}&group=${PHASE}&fleet=${FLEET}&name=${NAME}&host=${HOST}&port=${PORT}&user=${USER}" ${URL}`
+    ARR=(${RES})
+
+    if [ "${ARR[0]}" != "OK" ]; then
+        echo "Server Error. [${RES}]"
+        exit 1
+    fi
+
     echo "# yanolja toast config" > ${CONFIG}
     echo "LOGIN_URL=${LOGIN_URL}" >> ${CONFIG}
     echo "TOAST_URL=${TOAST_URL}" >> ${CONFIG}
@@ -333,25 +344,18 @@ config_save() {
     echo "PHASE=${PHASE}" >> ${CONFIG}
     echo "FLEET=${FLEET}" >> ${CONFIG}
     echo "NAME=${NAME}" >> ${CONFIG}
+
+    if [ "${ARR[2]}" != "" ]; then
+        HOST="${ARR[2]}"
+    fi
+
     echo "HOST=${HOST}" >> ${CONFIG}
     echo "PORT=${PORT}" >> ${CONFIG}
     echo "USER=${USER}" >> ${CONFIG}
     echo "TOKEN=${TOKEN}" >> ${CONFIG}
-
-    echo "server save..."
-
-    URL="${TOAST_URL}/server/config"
-    RES=`curl --data "token=${TOKEN}&no=${SNO}&group=${PHASE}&fleet=${FLEET}&name=${NAME}&host=${HOST}&port=${PORT}&user=${USER}" ${URL}`
-    ARR=(${RES})
-
-    if [ "${ARR[0]}" != "OK" ]; then
-        echo "Server Error."
-        exit 1
-    fi
-
     echo "SNO=${ARR[1]}" >> ${CONFIG}
 
-    echo "${ARR[0]} ${ARR[1]}"
+    echo "${RES}"
 }
 
 update_yum() {
@@ -484,7 +488,7 @@ version_next() {
     ARR=(${RES})
 
     if [ "${ARR[0]}" != "OK" ]; then
-        echo "Server Error."
+        echo "Server Error. [${RES}]"
         exit 1
     fi
 
@@ -520,7 +524,7 @@ version_save() {
     ARR=(${RES})
 
     if [ "${ARR[0]}" != "OK" ]; then
-        echo "Server Error."
+        echo "Server Error. [${RES}]"
         exit 1
     fi
 
